name: opencart
# type of products [Application(APP), Virtual Machine(VM), 
# Bare Metal(Bare)]
type: APP
description: |
  OpenCart is an open source PHP-based online
  e-commerce solution.
# author: TriClusters, Inc
version: 0.0.1
relationship:

deploy_police:
  name: 

questions:
  - name: cloud
    label: Cloud location
    description: |
      The Cloud location where product an deployed.
    type: string
    default: private.rancher
    required: true
    hidden: false
  - name: proxy_scheme
    label: Proxy scheme
    description: |
      When behind a proxy, specify the protocol clients will use to connect to Confluence
    type: enum
    options:
      - http
      - https
    default: http
    required: false
    hidden: false

docker:
  opencart:
    image: registry.databasemart.net:443/opencart2
    ports:
      - 80:80

rancher: