name: opencart
# type of products [Application(APP), Virtual Machine(VM), 
# Bare Metal(Bare)]
type: APP
description: |
  OpenCart is an open source PHP-based online
  e-commerce solution.
# author: TriClusters, Inc
version: 0.0.1
relationship:

deploy_police:
  name: 

questions:
  - name: cloud
    label: Cloud location
    description: |
      The Cloud location where product an deployed.
    type: string
    default: private.rancher
    required: true
    hidden: false
  - name: proxy_scheme
    label: Proxy scheme
    description: |
      When behind a proxy, specify the protocol clients will use to connect to Confluence
    type: enum
    options:
      - http
      - https
    default: http
    required: false
    hidden: false

docker:
  opencart:
    image: registry.databasemart.net:443/opencart3
    mem_limit: 1000000000
    cpu_quota: 50000
    ports:
      - 80:80
    labels:
      - app_plan=Basic
    volumes:
      - opencart_db:/var/lib/mysql
      - opencart_web:/var/www/html
    environment:
      - DB_PASSWORD=dbpassword

rancher:
  .catalog:
    name: "Opencart"
    version: "v1"
    description: "opencart"
    uuid: Opencart-0
    minimum_rancher_version: v0.51.0
    questions:
      - variable: public_port
        description: "public port to access the opencart site"
        label: "Public Port"
        required: true
        default: "80"
        type: "int"

  opencart: