name: wordpress
# type of products [Application(APP), Virtual Machine(VM), 
# Bare Metal(Bare)]
type: APP
description: |
  OpenCart is an open source PHP-based online
  e-commerce solution.
# author: TriClusters, Inc
version: 0.0.1
relationship:

deploy_police:
  name: 

questions:
  - name: cloud
    label: Cloud location
    description: |
      The Cloud location where product an deployed.
    type: string
    default: private.rancher
    required: true
    hidden: false
  - name: proxy_scheme
    label: Proxy scheme
    description: |
      When behind a proxy, specify the protocol clients will use to connect to Confluence
    type: enum
    options:
      - http
      - https
    default: http
    required: false
    hidden: false

docker:
  wordpress:
    image: wordpress
    links:
      - db:mysql
    ports:
      - 8088:80

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example  

rancher:
  .catalog:
    name: "Wordpress"
    version: "v0.1-educaas1"
    description: "Blog tool, publishing platform and CMS"
    uuid: Wordpress-0
    minimum_rancher_version: v0.51.0
    questions:    
      - variable: public_port
        description: "public port to access the wordpress site"
        label: "Public Port"
        required: true
        default: "80"
        type: "int"


  wordpress: