software_type: ECOM
software_name: magento
packages:
  # First Product Package infomation
  - name: express.mysql 
    version: 3.15.0
    # express, basic, advanced
    description:
    system: {}
    database: {} 
    target: 
    plans: 
      - express-linux
      - express-windows
  # Second Product Package infomation
  - name: express.mysql 
    version: 3.15.11
    # express, basic, advanced
    description:
    system: {}
    database: {} 
    target: 
    plans: 
      - express-linux
      - express-windows  
# product plan
plans:
  express-linux:
    cpu_cores: 10
    memory: 20
    disks: 
      ssd: 30
      sata: 100
    bandwidth: 20
    servers:
      - name: db_server
        description: database server
        cpu_cores: 2
        memory: 2     
        disks: 
          - ssd: 30
            sata: 100
        ip_address:
        user_name: admin
        password: admin
        applications:
          - name: mysql
            description: database
            url:
            user_name: root
            password: admin
          - name: apache
            description: web server
            url: 
            user_name: admin
            password: apache               
    fees:
      price: 0
      discount: 1.0
      
  express-windows:
    cpu_cores: 10
    memory: 20
    disks: 
      ssd: 30
      sata: 100
    bandwidth: 20
    servers:
      - name: web_server
        description: 
        cpu_cores: 2
        memory: 2
        disks: 
          - ssd: 30 
            sata: 100
        ip_address:
        user_name:
        password:
        applications:
          - name:
            description:
            url:
            user_name:
            password:
    fees: 
      price: ll
      discount: 1.0
